name: cv
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.797297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.40784052370005486
  lightness: 0.34317207968679453
  saturation: 0.5998258813435552
  rhythmicContrast: 0.259824136003002
purpose:
  - name: null
    item: null
    url: null
